stages:
    - Build
    - Package

variables:
    VERBOSE: "1"
    MSBUILDDISABLENODEREUSE: "1"

Build (Windows):
    stage: Build
    tags:
        - unity
        - windows
    script:
        - echo %cd%
        # correct syntax appears to be either:
        # double backslash in double quotes, or single backslash without quotes
        - set path=%path%;"C:\\Program Files\\Unity\\Editor"
        - echo %path%
        - mkdir Build
        - start /wait Unity.exe -quit -batchmode -serial %UNITY_CI_SERIAL% -username %UNITY_CI_USERNAME% -password %UNITY_CI_PASSWORD% -projectPath "%cd%" -buildWindows64Player "Build/PluginBuildTest.exe"
        - start /wait Unity.exe -quit -batchmode -serial %UNITY_CI_SERIAL% -username %UNITY_CI_USERNAME% -password %UNITY_CI_PASSWORD% -projectPath "%cd%" -exportPackage "Assets/FoveUnityPlugin" "Fove_Unity_Plugin.unitypackage"
    artifacts:
        expire_in: 1 week
        paths:
            - Build/*
            - Fove_Unity_Plugin.unitypackage

Make Release Package:
    stage: Package
    tags:
        - fove
        - linux
        - docker
    dependencies:
        - Build (Windows)
    script:
        - find .
        - export PLUGIN_VERSION=`cat Changelog.md | grep "##" | head -n1 | sed "s/## //"`
        - export ZIP_NAME="Unity_Plugin_$PLUGIN_VERSION"
        - mkdir "$ZIP_NAME"
        - mv Changelog.md "$ZIP_NAME/"
        - mv QuickStart.md "$ZIP_NAME/"
        - mv "FOVE Unity Plugin Guide.md" "$ZIP_NAME/"
        - mv LICENSE.txt "$ZIP_NAME/"
        - mv Fove_Unity_Plugin.unitypackage "$ZIP_NAME/"
        - zip -r "$ZIP_NAME.zip" "$ZIP_NAME"
        - find .
    artifacts:
        name: "FoveUnityPlugin"
        expire_in: 2 weeks
        paths:
            - Unity_Plugin*.zip

